[package]
name = "yzb64"
description = "Ytrizja base-64 specialization"
version = "0.1.0"
edition = "2021"
license = "ISC OR Apache-2.0"
repository = "https://github.com/YZITE/b64"

[dependencies]
base64 = "0.20.0-alpha.1"
once_cell = "1.10"
